apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: alejajessi/python:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000

apiVersion: v1
kind: Service
metadata:
  name: loadBalancer
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: python
